#!/usr/bin/env python
# -*- coding: utf-8 -*-
from bs4 import BeautifulSoup
import requests
import json


def saveImg(url, name):
    r = requests.get(url)
    if r.status_code == 200:
       with open('/Users/wuqiyan/Downloads/PyCharm/ZhiHu/IMG/'+name+'.jpg', 'wb') as f:
           for chunk in r.iter_content(1024):
               f.write(chunk)

def readTxt():
    file_name = "/Users/wuqiyan/Downloads/PyCharm/ZhiHu/cookies.txt"
    f = open(file_name, "r")
    txt= f.read()
    f.close()
    return txt
total_cookies=readTxt()
offset=10
start='-1'
headers2=headers={'Host':'www.zhihu.com','Connection':'keep-alive','Accept':'*/*','Origin':'https://www.zhihu.com','X-Requested-With':'XMLHttpRequest','X-Xsrftoken':'ba86ed1e1c541ab8d7fa43e4d14fd848','User-Agent':'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36','Content-Type':'application/x-www-form-urlencoded; charset=UTF-8','Referer':'https://www.zhihu.com/question/28385432','Accept-Encoding':'gzip, deflate, br','Accept-Language':'zh-CN,zh;q=0.8,en;q=0.6','Cookie':total_cookies}
params={'params':'{"offset":'+str(offset)+',"start":"'+start+'"}','method':'next'}
proxies = {
    "https": "https://104.199.164.59:80"
}
g=requests.post('https://www.zhihu.com/node/TopStory2FeedList',headers=headers2,data=params,proxies=proxies)
if 'msg' in g.text:
    list=json.loads(g.text)['msg']
    if len(list)>0:
        for t in json.loads(g.text)['msg']:
            soup = BeautifulSoup(t, 'html5lib')
            print soup.h2.string
            authors= soup.find_all("a", class_="author-link")
            src=soup.find_all("img",class_="zm-item-img-avatar")
            link=soup.find_all("a",class_="zm-item-link-avatar")
            if len(authors)>0:
                name= authors[0].string
                url= src[0]['src']
                index=link[0]['href']
                print name,url,"https://www.zhihu.com/"+index
                saveImg(url,name)
            else:
                print '匿名用户'
else:
    print '返回格式错误:'+g
